name: Build Android Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
      with:
        repository: ederevx/x-ft_kernel_oneplus_msm8998

    - name: Add KernelSU
      run: |
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5

    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y gcc make git wget

    - name: Build kernel
      run: |
        # 简单编译
        make O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- defconfig
        make -j$(nproc) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-android-

    - name: Save output
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: out/arch/arm64/boot/
